### ISSUE TITLE
mods to look at adding

### ISSUE THREAD

**Issue by killer130112** [DatSquirrel7/ArcanaTechnika#1]
openblock elevator , towns and towers , when dungeons arise , construction wand , trash cans , dungeon crawl , reliquary , simple magnets , gateways to eternity , iron's spells n spellbooks , rsinfinity booster , extra storage , apothic attrubutes , cable tiers , stalwart dungeons , chance cubes , all the add-ons for silent gear that is in its overview , silentgear compat ,

**Comment by DatSquirrel7** [comment]
All mods have been added except for silent gear mods, none are available for 1.20
