### ISSUE TITLE
Lost items/backpack glitch

### ISSUE THREAD

**Issue by paxtone91** [DatSquirrel7/ArcanaTechnika#10]
when server was updated from 1.3 to 1.4/1.4.1 contents of backpacks were lost. after talking with Adam it seems to be linked to anything that was tied to an upgrade or memory slot, as he had some items that were not deleted. (entirety of my contents were memory slotted at time of update) all upgrades were also lost during update.

**Comment by DatSquirrel7** [comment]
Sophisticated Storage data was corrupted during restart. Notify an admin when logged in to receive items.
