### ISSUE TITLE
new mod idea

### ISSUE THREAD

**Issue by Foxdemon666** [DatSquirrel7/ArcanaTechnika#12]
Multipart Machines: Grinding
By Grabolit     and
Shrink.
By Gigabit101

**Comment by DatSquirrel7** [comment]
Shrink has stability issues and can cause server crashes. The grinding mod is very similar to hostile neural networks and the reason it was not added was to prevent the "afk farming" play style that a lot of other packs have. We have mob grinding utils if you would like to create a mob grinder.
