### ISSUE TITLE
mod suggestions 

### ISSUE THREAD

**Issue by Foxdemon666** [DatSquirrel7/ArcanaTechnika#2]
minecolonies, Starter Kit
 By
 [Serilum], When Dungeons Arise - Forge! By [Aureljz], and Small Ships [Fabric & Forge]
 By
 [talhanation]

**Comment by DatSquirrel7** [comment]
When Dungeons Arise has already been added.
Minecolonies is undergoing testing, I am unsure if it will be added.
Small Ships is definitely under consideration
Starter Kit is denied.

**Comment by Foxdemon666** [comment]
**mystical agriculture and it addon's, NoMoWanderer By TheJDill** , MEGA Cells By ninety, Applied Energistics 2 By thetechnici4n, Ars Énergistique By ninety, Applied Botanics Addon By ramidzkh, and Applied Mekanistics By ramidzkh

possible mods but the first two are a must
