### ISSUE TITLE
new mod idles

### ISSUE THREAD

**Issue by Foxdemon666** [DatSquirrel7/ArcanaTechnika#6]
messup

**Comment by Foxdemon666** [comment]
**mystical agriculture and it addon's, NoMoWanderer By TheJDill** , MEGA Cells By ninety, Applied Energistics 2 By thetechnici4n, Ars Énergistique By ninety, Applied Botanics Addon By ramidzkh, and Applied Mekanistics By ramidzkh

possible mods but the first two are a must

**Comment by DatSquirrel7** [comment]
Mystical Agriculture was not added for the point of making the game an AFK game. We were actively trying to avoid that. It will not be added at this time. 

I will have a follow up question regarding Applied Energistics. What specific items are you requesting the mod for? I had proposed this question myself and could not find a compelling argument for a reason to add it.

**Comment by Foxdemon666** [comment]
Ars Énergistique for  Ars Nouveau, Applied Botanics Addon for Botania, and Applied Mekanistics for Mekanism to make the mods more interactive with each other for storage and crafting

**Comment by Foxdemon666** [comment]
I'm ok with not having Mystical Agriculture I just wanted a way to speedup plant growth without having to farm a shit ton of bonemeal. 
also possible mods Pam's HarvestCraft 2

**Comment by DatSquirrel7** [comment]
Yes, but that doesn't answer the question. Why add Applied Energistics specifically? I understand the compat mods, but not the core mod itself.

**Comment by DatSquirrel7** [comment]
Pam's Harvestcraft is not needed as we already have Croptopia and Farming for Blockheads. As far as faster growing, Farming for Blockheads has Red Fertilizer which will achieve the result you are after.
