### ISSUE TITLE
mod ideas

### ISSUE THREAD

**Issue by killer130112** [DatSquirrel7/ArcanaTechnika#7]
Random Walmarts by yadarb , Explorify – Dungeons & Structures by bebebea_loste (more explor things) , Integrated Dungeons and Structures by CraisinLord , Awesome Dungeon Ocean edition - Forge by jtl_elisa , 

mods for more in exploring as i like to have lots of shit to loot

**Comment by DatSquirrel7** [comment]
We have plenty of structure mods at this time. Any more will cause world generation lag that we do not desire.
