### ISSUE TITLE
mod

### ISSUE THREAD

**Issue by Foxdemon666** [DatSquirrel7/ArcanaTechnika#9]
Structory and Structory: Towers

**Comment by Foxdemon666** [comment]
MVS - Moog's Voyager Structures

**Comment by Foxdemon666** [comment]
Better Archeology By Pandarix

**Comment by Foxdemon666** [comment]
Fantasy's Furniture By ApexModder

**Comment by Foxdemon666** [comment]
MC Dungeons Weapons By chronos_sacaria
and other MC Dungeon Mods

**Comment by Foxdemon666** [comment]
Dreadsteel By DaddyUnion

**Comment by Foxdemon666** [comment]
Map Atlases [Forge] By MehVahdJukaar

**Comment by Foxdemon666** [comment]
Mob spawners and eggs recipes By Draggonfire1

**Comment by Foxdemon666** [comment]
TrimsEffects By Lupin

**Comment by DatSquirrel7** [comment]
TrimsEffects, Better Archeology, and Fantasy's Furniture have been added. Other mods usecases are filled by Silent Gear and other mods.
